version: "3.8"

services:
  # Core nodes
  dfs_core:
    image: dfs_core:latest
    build: .
    deploy:
      mode: replicated
      replicas: 3
      labels:
        - "node_type=core"
    environment:
      - NODE_TYPE=core
      - QUORUM_SIZE=2
    ports:
      - target: 8000
        published: 30000
        protocol: tcp
        mode: host
    volumes:
      - type: volume
        source: dfs_core_data
        target: /app/data
    networks:
      - dfs_network

  # Edge nodes
  dfs_edge:
    image: dfs_edge:latest
    build: .
    deploy:
      mode: replicated
      replicas: 2
      labels:
        - "node_type=edge"
    environment:
      - NODE_TYPE=edge
      - DEVICE_TYPE={{.Task.Slot}}  # Will be 1=mobile, 2=iot
    ports:
      - target: 8000
        published: 30010
        protocol: tcp
        mode: host
    volumes:
      - type: volume
        source: dfs_edge_data
        target: /app/data
    networks:
      - dfs_network

  # Monitoring stack
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    deploy:
      mode: replicated
      replicas: 1
    networks:
      - dfs_network

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - type: bind
        source: ./grafana/dashboards
        target: /etc/grafana/provisioning/dashboards
      - type: bind
        source: ./grafana/provisioning/dashboards
        target: /etc/grafana/provisioning/dashboards/config
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SECURITY_ADMIN_USER=admin
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
    networks:
      - dfs_network

networks:
  dfs_network:
    driver: overlay
    attachable: true

volumes:
  dfs_core_data:
    driver: local
  dfs_edge_data:
    driver: local
