global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'dfs_nodes'
    dns_sd_configs:
      - names:
        - 'tasks.dfs_core'  # Docker Swarm DNS name for core nodes
        - 'tasks.dfs_edge'  # Docker Swarm DNS name for edge nodes
        type: 'A'
        port: 8000
        refresh_interval: 30s
    relabel_configs:
      - source_labels: [__meta_dns_name]
        regex: 'tasks\.dfs_(.*)'
        target_label: node_type
        replacement: '$1'
      - source_labels: [__address__]
        target_label: instance
        regex: '(.*):.+'
        replacement: '$1'

  - job_name: 'load_testing'
    dns_sd_configs:
      - names: ['tasks.locust']
        type: 'A'
        port: 8089
    
  - job_name: 'locust_metrics'
    dns_sd_configs:
      - names: ['tasks.locust']
        type: 'A'
        port: 9100
    relabel_configs:
      - target_label: service
        replacement: 'locust'
