apiVersion: skaffold/v4beta5
kind: Config
metadata:
  name: distributed-file-system
build:
  artifacts:
    - image: dfs-storage-node
      context: .
      docker:
        dockerfile: src/storage-node/Dockerfile
        buildArgs:
          SERVICE_PATH: src/storage-node
      sync:
        manual:
          - src: "src/storage-node/**/*.go"
            dest: .
    - image: dfs-csi-driver
      context: .
      docker:
        dockerfile: src/csi/Dockerfile
        buildArgs:
          SERVICE_PATH: src/csi
      sync:
        manual:
          - src: "src/csi/**/*.py"
            dest: .
          - src: "src/csi/requirements.txt"
            dest: .
    - image: dfs-api
      context: .
      docker:
        dockerfile: src/api/Dockerfile
        buildArgs:
          SERVICE_PATH: src/api
      sync:
        manual:
          - src: "src/api/**/*.py"
            dest: .
          - src: "src/api/requirements.txt"
            dest: .
    - image: dfs-monitoring
      context: .
      docker:
        dockerfile: src/monitoring/Dockerfile
        buildArgs:
          SERVICE_PATH: src/monitoring
      sync:
        manual:
          - src: "src/monitoring/**/*.py"
            dest: .
          - src: "src/monitoring/requirements.txt"
            dest: .
  local:
    push: false
    useBuildkit: true

manifests:
  rawYaml:
    - src/k8s/base/*
    - src/k8s/overlays/development/*

deploy:
  kubectl: {}

profiles:
  - name: dev
    activation:
      - kubeContext: docker-desktop
    patches:
      - op: add
        path: /build/local/push
        value: false

  - name: prod
    patches:
      - op: add
        path: /build/local/push
        value: true
    manifests:
      rawYaml:
        - src/k8s/base/*
        - src/k8s/overlays/production/*
