apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: dfs-node
  namespace: distributed-fs
spec:
  serviceName: dfs-service
  replicas: 2
  selector:
    matchLabels:
      app: dfs-node
  template:
    metadata:
      labels:
        app: dfs-node
    spec:
      containers:
      - name: dfs-node
        image: dfs-node:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
          name: api
        - containerPort: 9090
          name: metrics
        volumeMounts:
        - name: data
          mountPath: /data
        env:
        - name: NODE_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: STORAGE_ENV
          value: "hybrid"
        - name: MINIKUBE_ENV
          value: "true"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: dfs-hybrid-storage
      resources:
        requests:
          storage: 1Gi
