apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitoring-service
  namespace: distributed-fs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monitoring-service
  template:
    metadata:
      labels:
        app: monitoring-service
    spec:
      containers:
      - name: monitoring-service
        image: python:3.8.13-slim
        workingDir: /app
        command: ["/bin/sh", "-c"]
        args:
          - |
            pip install -r requirements.txt
            python src/monitoring/app.py
        ports:
        - containerPort: 5000
        env:
        - name: PORT
          value: "5000"
        volumeMounts:
        - name: app-code
          mountPath: /app
      volumes:
      - name: app-code
        hostPath:
          path: /Users/kevinklatman/Development/Code/DistributedFileSystem
---
apiVersion: v1
kind: Service
metadata:
  name: monitoring-service
  namespace: distributed-fs
spec:
  type: NodePort
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30500
  selector:
    app: monitoring-service
