apiVersion: v1
kind: ServiceAccount
metadata:
  name: storage-node-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: storage-node-role
rules:
- apiGroups: [""]
  resources: ["pods", "nodes"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  verbs: ["create", "get", "list", "update", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: storage-node-role-binding
subjects:
- kind: ServiceAccount
  name: storage-node-sa
roleRef:
  kind: Role
  name: storage-node-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: dfs-storage-node
  namespace: distributed-fs
spec:
  serviceName: dfs-storage
  replicas: 3
  selector:
    matchLabels:
      app: dfs-storage-node
  template:
    metadata:
      labels:
        app: dfs-storage-node
    spec:
      serviceAccountName: storage-node-sa
      containers:
      - name: storage-node
        image: dfs-storage:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
        env:
        - name: NODE_TYPE
          value: "storage"
        - name: NODE_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        volumeMounts:
        - name: data
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: dfs-storage
spec:
  clusterIP: None
  selector:
    app: dfs-storage-node
  ports:
  - port: 8080
    targetPort: 8080
    name: http
