apiVersion: apps/v1
kind: Deployment
metadata:
  name: dfs-monitoring
  namespace: distributed-fs
  labels:
    app: dfs-monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dfs-monitoring
  template:
    metadata:
      labels:
        app: dfs-monitoring
    spec:
      serviceAccountName: dfs-monitoring-sa
      containers:
      - name: monitoring
        image: dfs-monitoring:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: dfs-monitoring
  namespace: distributed-fs
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5000
    protocol: TCP
  selector:
    app: dfs-monitoring
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dfs-monitoring-sa
  namespace: distributed-fs
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-reader
  namespace: distributed-fs
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-reader-binding
  namespace: distributed-fs
subjects:
- kind: ServiceAccount
  name: dfs-monitoring-sa
  namespace: distributed-fs
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io
