apiVersion: v1
kind: ServiceAccount
metadata:
  name: storage-node-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: storage-node-role
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  verbs: ["create", "get", "list", "watch", "update", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: storage-node-binding
subjects:
- kind: ServiceAccount
  name: storage-node-sa
  namespace: default
roleRef:
  kind: ClusterRole
  name: storage-node-role
  apiGroup: rbac.authorization.k8s.io
