apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-dfs-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: dfs-hybrid-storage
