apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: dfs-hybrid-storage
provisioner: dfs.csi.k8s.io
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true
parameters:
  type: "hybrid"  # Can be configured based on your storage requirements
