# api-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: dfs-api-service
  labels:
    app: dfs-api
spec:
  selector:
    app: dfs-api
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080
  type: NodePort
