apiVersion: v1
kind: Service
metadata:
  name: dfs-api-service
  labels:
    app: dfs-api
spec:
  selector:
    app: dfs-api
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30083
    - name: metrics
      protocol: TCP
      port: 9090
      targetPort: 9090
      nodePort: 30093
  type: NodePort
