apiVersion: v1
kind: ConfigMap
metadata:
  name: dfs-api-files
data:
  requirements.txt: |
    flask==2.2.2
    flask-cors==3.0.10
    gunicorn==21.2.0
    python-dotenv==1.0.0
    xmltodict==0.13.0
    werkzeug>=3.0.0
    kubernetes==29.0.0
    prometheus-client==0.17.1
    psutil==5.9.6
    pytest>=7.4.0
    pytest-mock>=3.11.1
    matplotlib>=3.7.0
    numpy>=1.24.0
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dfs-api
  labels:
    app: dfs-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dfs-api
  template:
    metadata:
      labels:
        app: dfs-api
    spec:
      containers:
      - name: dfs-api
        image: dfs-api:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        command: ["python"]
        args: ["-m", "api.app"]
        env:
        - name: PYTHONPATH
          value: /app/src
        - name: FLASK_APP
          value: api/app.py
        - name: FLASK_ENV
          value: production
        volumeMounts:
        - name: storage-volume
          mountPath: /app/storage
      volumes:
      - name: storage-volume
        emptyDir: {}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dfs-storage-claim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
