apiVersion: apps/v1
kind: Deployment
metadata:
  name: dfs-api
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dfs-api
  template:
    metadata:
      labels:
        app: dfs-api
    spec:
      containers:
      - name: dfs-api
        image: dfs-api:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
        - name: STORAGE_ROOT
          value: "/data/dfs"
        - name: API_HOST
          value: "0.0.0.0"
        - name: API_PORT
          value: "8080"
        - name: DEBUG
          value: "false"
        volumeMounts:
        - name: dfs-storage
          mountPath: /data/dfs
      volumes:
      - name: dfs-storage
        persistentVolumeClaim:
          claimName: dfs-pvc
