apiVersion: apps/v1
kind: Deployment
metadata:
  name: dfs-api
  labels:
    app: dfs-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dfs-api
  template:
    metadata:
      labels:
        app: dfs-api
    spec:
      containers:
      - name: dfs-api
        image: dfs-api:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
        - name: PYTHONPATH
          value: "/app/src"
        - name: LOCAL_STORAGE_DIR
          value: "/app/storage"
        - name: API_HOST
          value: "0.0.0.0"
        - name: API_PORT
          value: "8080"
        - name: FLASK_ENV
          value: "production"
        volumeMounts:
        - name: storage-volume
          mountPath: /app/storage
      volumes:
      - name: storage-volume
        persistentVolumeClaim:
          claimName: dfs-storage-claim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dfs-storage-claim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
