# k8s/base/aws-ebs-csi-driver.yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: dfs-ebs-sc
provisioner: ebs.csi.aws.com
parameters:
  type: gp3
  encrypted: "true"
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
