---
# AWS Credentials
apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
  namespace: distributed-fs
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
  AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
  AWS_REGION: "${AWS_REGION:-us-east-2}"
---
# Google Cloud Credentials
apiVersion: v1
kind: Secret
metadata:
  name: gcp-credentials
  namespace: distributed-fs
type: Opaque
stringData:
  # Base64 encoded service account key
  GOOGLE_APPLICATION_CREDENTIALS: "${GOOGLE_APPLICATION_CREDENTIALS}"
  GOOGLE_CLOUD_PROJECT: "${GOOGLE_CLOUD_PROJECT}"
---
# Azure Credentials
apiVersion: v1
kind: Secret
metadata:
  name: azure-credentials
  namespace: distributed-fs
type: Opaque
stringData:
  AZURE_STORAGE_CONNECTION_STRING: "${AZURE_STORAGE_CONNECTION_STRING}"
  AZURE_STORAGE_ACCOUNT: "${AZURE_STORAGE_ACCOUNT}"
  AZURE_STORAGE_KEY: "${AZURE_STORAGE_KEY}"
