# k8s/base/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dfs-api
  namespace: distributed-fs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dfs-api
  template:
    metadata:
      labels:
        app: dfs-api
    spec:
      containers:
      - name: dfs-api
        image: distributed-fs:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
        - name: STORAGE_ENV
          value: "aws"
        - name: AWS_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: AWS_ACCESS_KEY
        - name: AWS_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: AWS_SECRET_KEY
        - name: AWS_REGION
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: AWS_REGION
        - name: API_HOST
          value: "0.0.0.0"
        - name: API_PORT
          value: "8080"
        - name: LOCAL_STORAGE_DIR
          value: "/app/storage"
        - name: PYTHONPATH
          value: "/app/src"
        - name: DEBUG
          value: "False"
        - name: FLASK_ENV
          value: "production"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
