# k8s/base/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - api-deployment.yaml
  - api-service.yaml
  - configmap.yaml
  - secret.yaml
  - storage-node-crd.yaml
  - storage-node-rbac.yaml
  - storage-node-deployment.yaml
  - csi-driver.yaml
  - test-pvc.yaml
  - test-pod.yaml

commonLabels:
  app: dfs-node
  environment: base
