# k8s/base/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dfs-system

resources:
  - namespaces/dfs-system.yaml
  - api-deployment.yaml
  - api-service.yaml
  - configmap.yaml
  - secret.yaml
  - storage-node-crd.yaml
  - storage-node-rbac.yaml
  - storage-node-deployment.yaml
  - csi-driver.yaml
  - test-pvc.yaml
  - test-pod.yaml
  - service.yaml

commonLabels:
  app: dfs-node
  part-of: distributed-file-system
