# k8s/base/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
  - api-deployment.yaml
  - api-service.yaml
  - storage-node-deployment.yaml
  - service.yaml
  - csi-driver.yaml

configMapGenerator:
  - name: dfs-config
    literals:
      - API_HOST=0.0.0.0
      - API_PORT=61478
      - DEBUG=False
      - FLASK_ENV=production
