apiVersion: v1
kind: Service
metadata:
  name: dfs-storage-service
  labels:
    app: dfs-storage-node
spec:
  selector:
    app: dfs-storage-node
  ports:
    - name: http
      protocol: TCP
      port: 8081
      targetPort: 8081
    - name: metrics
      protocol: TCP
      port: 9091
      targetPort: 9091
  type: ClusterIP
