apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: dfs-hybrid-storage
provisioner: dfs.csi.k8s.io
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
parameters:
  type: "hybrid"
  minikube.storage.path: "/data/dfs"
