apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: dfs-storage
  namespace: default
  labels:
    app.kubernetes.io/part-of: distributed-file-system
provisioner: dfs.csi.k8s.io
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
parameters:
  type: "hybrid"
  tier: "standard"
