# k8s/base/backup-plan.yaml
apiVersion: aws.upbound.io/v1beta1
kind: BackupPlan
metadata:
  name: dfs-backup-plan
spec:
  forProvider:
    region: us-west-2
    rules:
    - ruleName: daily-backup
      targetVaultName: dfs-backup-vault
      scheduleExpression: "cron(0 5 ? * * *)"
      startWindowMinutes: 60
      completionWindowMinutes: 120
      lifecycle:
        deleteAfterDays: 14
