# k8s/base/deployment.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: dfs-storage
  namespace: dfs-system
spec:
  serviceName: dfs-storage
  replicas: 3
  selector:
    matchLabels:
      app: dfs-storage
  template:
    metadata:
      labels:
        app: dfs-storage
    spec:
      containers:
      - name: dfs-storage
        image: your-registry/dfs-storage:latest
        ports:
        - containerPort: 50051
          name: grpc
        - containerPort: 9090
          name: metrics
        volumeMounts:
        - name: data
          mountPath: /data
        resources:
          requests:
            cpu: 500m
            memory: 1Gi
          limits:
            cpu: 1000m
            memory: 2Gi
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: dfs-ebs-sc
      resources:
        requests:
          storage: 100Gi
