# k8s/base/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - pv.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - hpa.yaml

commonLabels:
  app: dfs-node
  environment: base
