# storage-pv.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: dfs-storage-pv
  namespace: dfs-system
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  hostPath:
    path: "/mnt/data"
