# storage-pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dfs-storage-pvc
  namespace: dfs-system
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
