# storage-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
  namespace: distributed-fs
type: Opaque
stringData:
  AWS_ACCESS_KEY: your-access-key-here
  AWS_SECRET_KEY: your-secret-key-here
  AWS_REGION: us-east-2
